name: CMake on Windows with vcpkg

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clean and clone vcpkg
      run: |
        Remove-Item -Recurse -Force C:\vcpkg -ErrorAction SilentlyContinue
        git clone https://github.com/microsoft/vcpkg.git C:\vcpkg

    - name: Bootstrap vcpkg
      run: C:\vcpkg\bootstrap-vcpkg.bat

    - name: Install dependencies
      run: |
        C:\vcpkg\vcpkg.exe install pugixml:x64-windows
        C:\vcpkg\vcpkg.exe install nlohmann-json:x64-windows
        C:\vcpkg\vcpkg.exe install cli11:x64-windows

    - name: Configure CMake
      run: |
        cmake -B build `
          -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake `
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}